### ISSUE TITLE
Installation : ModuleNotFoundError: No module named 'rdf_io.protocols'

### ISSUE THREAD

**Issue by AnasGhrab** [rob-metalinkage/django-rdf-io#14]
Hi,

I get the error ```ModuleNotFoundError: No module named 'rdf_io.protocols'``` when I run ```makemigrations``` for the first time.

I don't know if it's related but as I'm using Django 3.0, I also get the error ```django 3.0.4 - cannot import name 'python_2_unicode_compatible'```; so I have replaced ```from django.utils.encoding import python_2_unicode_compatible``` with: ```from six import python_2_unicode_compatible``` (as indicaed here https://github.com/pinax/pinax-blog/issues/128).

**Comment by rob-metalinkage** [comment]
Thanks -  just assimilating some updates to support python3 - feel free to generate a pull request.
am working on making the post-processing pipeline more flexible now rdflib is under active maintenance again - so please feel free to drop me a line about your requirements and Use Cases if you want any help.

**Comment by rob-metalinkage** [comment]
commit 9446206e9b06820560d3141c7c5dccd83aae5d40 should have fixed this...

Warning - need to run migrate on new project before installing rdf_io.

**Comment by AnasGhrab** [comment]
Thank you.. but I still have to same problem (a fresh project)
```
anas@Zeus:~/www/testrdf$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    main()
  File "./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/dist-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/dist-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/rdf_io/models.py", line 2, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/usr/local/lib/python3.8/dist-packages/django/utils/encoding.py)

```
